name: Update Cache ID and Push Changes

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-cache-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name "matahariku"
          git config user.email "action@github.com"
      - name: Update Cache ID
        run: |
          echo "ID=$(date +%s)" > .ansible_cache_id
          git add .ansible_cache_id
          git commit -m "Update Ansible Cache ID"
          git push


