name: Caching with pip
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v3
        env:
          cache-name: cache-pip-packages
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-pip.outputs.cache-hit != 'true' }}
        name: List installed packages
        run: pip list

      - name: Install Ansible
        run: |
          python -m pip install ansible

      - name: Test ansible
        run: ansible all -i inventory -m ping

