name: Ansible Conditional Execution

on: [push, pull_request, workflow_dispatch]

jobs:
  ansible-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Cached ID
        id: cache-id
        uses: actions/cache@v2
        with:
          path: '.ansible_cache_id'
          key: ${{ runner.os }}-ansible-id

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Define the Python version.

      - name: Install Ansible
        if: steps.cache-id.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-ansible-${{ hashFiles('**/*.yml') }}

      - name: Run Ansible Playbook
        if: steps.cache-id.outputs.cache-hit != 'true'
        run: |
          ansible-playbook -i inventory playbook.yml
          echo "ID=$(date +%s)" > .ansible_cache_id

      - name: Update Cache ID
        if: steps.cache-id.outputs.cache-hit != 'true'
        run: |
          git config --global user.name "matahariku"
          git config --global user.email "farida.eryani@gmail.com"
          git add .ansible_cache_id
          git commit -m "Update Ansible Cache ID"
          git push


