name: Ansible Conditional Execution

on: [push, workflow_dispatch]

jobs:
  ansible-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Cached ID
        id: cache-id
        uses: actions/cache@v2
        with:
          path: '.ansible_cache_id'
          key: ${{ runner.os }}-ansible-id

      - name: Run Ansible if ID is not cached
        if: steps.cache-id.outputs.cache-hit != 'true'
        run: |
          # Run your Ansible playbook here
          ansible-playbook -i inventory playbook.yml
          # Assuming the playbook execution is successful, update the cache ID
          echo "ID=$(date +%s)" > .ansible_cache_id
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .ansible_cache_id
          git commit -m "Update Ansible Cache ID"
          git push

      - name: Setup caching for future runs
        uses: actions/cache@v2
        with:
          path: '.ansible_cache_id'
          key: ${{ runner.os }}-ansible-id-new
          restore-keys: |
            ${{ runner.os }}-ansible-id
