name: Caching with pip
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pip packages
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-pip-

      - if: ${{ steps.cache-pip.outputs.cache-hit != 'true' }}
        name: List installed packages
        run: pip list

      - name: Install dependencies
        run: |
          pip install ansible

      - name: Install pytest
        run: python -m pip install pytest

      - name: Run test
        run: pytest

