name: Setup and Install Dependencies

on: [pull_request, workflow_dispatch]

jobs:
  setup-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check Initialization State
        id: check_state
        run: |
          if [ -f '.ansible_initialized' ]; then
            echo "INITIALIZED=true" >> $GITHUB_ENV
          else
            echo "INITIALIZED=false" >> $GITHUB_ENV
          fi
          echo "ANSIBLE_ID=${{ github.event.inputs.ansible_id }}" >> $GITHUB_ENV

      - name: Install Ansible and other requirements conditionally
        if: env.INITIALIZED == 'false' || env.PREV_ID != env.ANSIBLE_ID
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          echo "${{ github.event.inputs.ansible_id }}" > .ansible_executed_id
          touch .ansible_initialized
          git add .ansible_executed_id .ansible_initialized
          git commit -m "Initial setup completed and Ansible execution ID updated"
          git push

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip

