name: Python Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Check for existing INSTALL_ID
        id: check_id
        run: |
          if [ -f .ansible_cache_id ]; then
            echo "::set-output name=install_id::$(cat .ansible_cache_id)"
          else
            echo "::set-output name=install_id::"
          fi

      - name: Generate INSTALL_ID if not exists
        if: steps.check_id.outputs.install_id == ''
        run: echo "INSTALL_ID=$(date +%s)-$(ansible --version | sha256sum | head -c 64)" > .ansible_cache_id

      - name: Display INSTALL_ID
        run: cat .ansible_cache_id

      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"

      - name: Commit and Push INSTALL_ID
        run: |
          git add .ansible_cache_id
          git commit -m "Update Ansible Cache ID"
          git push


