name: Setup and Install Dependencies

on: [push, pull_request]  # Trigger the workflow on push and pull request events

jobs:
  setup-and-install:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - name: Checkout code
<<<<<<< HEAD
        uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE
=======
        uses: actions/checkout@v2  # Checks out my repository under $GITHUB_WORKSPACE
>>>>>>> 3c81240f54671296f352f03a0cadbc04a3482572

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Setup Python version 3.x

      - name: Install Ansible and other requirements
        run: |
          python -m pip install --upgrade pip >/dev/null 2>&1
          python -m pip install -r requirements.txt >/dev/null 2>&1
<<<<<<< HEAD
=======

>>>>>>> 3c81240f54671296f352f03a0cadbc04a3482572
