name: Ansible Installation with Python Package Caching

on: [push, pull_request, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate installation ID based on relevant files
        id: gen_id
        run: echo "INSTALL_ID=$(date +%s)-$(sha256sum **/*.py | sha256sum)" | tee .ansible_cache_id

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ steps.gen_id.outputs.INSTALL_ID }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Ansible
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Display the Generated ID
        run: cat .ansible_cache_id


