name: Install Ansible and Generate ID

on:
  push:
    branches:
      - main

jobs:
  setup-and-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Generate INSTALL_ID based on Ansible installation
        run: |
          ANSIBLE_VERSION=$(ansible --version | head -1)
          DATE=$(date +%s)
          HASH=$(echo "${DATE}_${ANSIBLE_VERSION}" | sha256sum | awk '{print $1}')
          echo "INSTALL_ID=${DATE}-${HASH}" > .ansible_cache_id
          echo "INSTALL_ID=${DATE}-${HASH}"

      - name: Commit INSTALL_ID to repository
        run: |
          git config --global user.name "farida-eryani"
          git config --global user.email "farida.eryani@esante-bretagne.fr"
          git add .ansible_cache_id
          git commit -m "Update Ansible Cache ID"
          git push

      - name: Use INSTALL_ID
        run: cat .ansible_cache_id

